included:
  - CoreExtension/Sources
excluded:
  - Pods
  
disabled_rules:
  - trailing_whitespace
#  - todo
#  - function_body_length
#  - line_length
  - identifier_name
  - multiple_closures_with_trailing_closure
  - comment_spacing
  - type_body_length
  - file_length
  
#warning_threshold: 1

reporter: "xcode"
